= nocolor
:project: hugo-theme-nocolor
:uri-base: https://schlomp.space/tastytea/{project}
:uri-hugo: https://gohugo.io/
:uri-slick: https://github.com/spookey/slick
:uri-slick-example: {uri-slick}/blob/master/_sites/example/config.toml
:uri-opengraph: http://ogp.me/
:uri-schema: https://schema.org/
:uri-twittercards: https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/abouts-cards.html
:uri-hugo-doc-toc: https://gohugo.io/content-management/toc
:uri-tomorrow-pygments: https://github.com/mozmorris/tomorrow-pygments

*nocolor* is a link:{uri-hugo}[Hugo] theme with no predefined colors and minimal
styling. It is based on link:{uri-slick}[Slick].

== Features

* Supports taxonomies of tags, categories and series with their own pages.
* RSS Feed with complete entries.
* link:{uri-opengraph}[Open Graph], link:{uri-schema}[Schema.org] and
  link:{uri-twittercards}[Twitter Cards] support.
* Fully customizable menu entries.
* No JavaScript, no bundled fonts, no external requests.

== Installation

[source,shell]
--------------------------------------------------------------------------------
git submodule add https://schlomp.space/tastytea/hugo-theme-nocolor.git themes/nocolor
echo 'theme = "nocolor"' >> config.toml
--------------------------------------------------------------------------------

== Configuration & Modification

Please take a look at the link:{uri-slick-example}[configuration example for
Slick]. It is valid for nocolor too.

You can add things to the end of the `<head>` section by overwriting the partial
template `extra-head.html` or above the footer by overwriting
`extra_foot.html`. The common way to do it is to create
`layouts/partials/extra_head.html` or `layouts/partials/extra_foot.html`,
respectively.

If you want source code highlighting, take a look at
link:{uri-tomorrow-pygments}[tomorrow-pygments].

== Good to know

Table of contents are only written when the word count exceeds 400 and the `toc`
field in your content’s front matter is set to true. See
link:{uri-hugo-doc-toc}[the Hugo documentation] for details. You can overwrite
the template by adding the file `layouts/partials/toc.html` to your blog.

include::{uri-base}/raw/branch/main/CONTRIBUTING.adoc[]
