name = "nocolor"
license = "MIT"
licenselink = "https://opensource.org/licenses/MIT"
description = "A Hugo theme with no predefined colors."
homepage = "https://schlomp.space/tastytea/hugo-theme-nocolor"
tags = ["blog", "minimal", "clean", "no js", "light"]
features = ["blog", "fulltext rss feed"]
min_version = "0.60"

[author]
    name = "tastytea"
    homepage = "https://tastytea.de/"

[original]
    name = "Frieder Grießhammer"
    homepage = "https://www.der-beweis.de/"
    repo = "https://github.com/spookey/slick"
